#@ load("@ytt:data", "data")
---
esphome:
  name: #@ data.values.device.name
  comment: #@ data.values.device.description

substitutions:
  version: #@ data.values.version.strip()

esp8266:
  board: d1_mini

logger:
  level: DEBUG

wifi:
  ssid: #@ data.values.wifi.ssid.strip()
  password: #@ data.values.wifi.password.strip()

web_server:
  port: 80

prometheus:
  include_internal: true
  relabel:
    firmware:
      name: #@ data.values.device.name + "_" + data.values.version.strip().replace(".", "_")

sensor:
  - platform: template
    id: firmware
    lambda: return 1;
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor
